#include <iostream>
#include <stdexcept>
using namespace std;

class InsufficientFundsException : public exception {
private:
    string err;
public:
    InsufficientFundsException(const char* message) : err(message){}
    
    const char* what() const throw(){
        return err.c_str();
    }
};

class BankAccount {
public:
    int accountNumber;
    string accountHolder;
    double balance;

    BankAccount(int accountNumber, const string& accountHolder, double balance)
        : accountNumber(accountNumber), accountHolder(accountHolder), balance(balance) {}

    double getBalance() const {
        return balance;
    }

    void withdraw(double amount) {
        if (amount > balance) {
            throw InsufficientFundsException("Insufficient funds. Withdrawal not allowed.");
        }
        balance -= amount;
    }
};

int main() {
    try {
        BankAccount account1(1001, "Alice", 1000.0);
        account1.withdraw(2000.0); 
        cout << "Account 1 Balance: " << account1.balance << endl;
    }
    catch (const InsufficientFundsException& ex) {
        cout << "Exception: " << ex.what() << endl;
    }

    return 0;
}
